# See https://github.com/dangoslen/dependabot-changelog-helper for more info
name: Dependabot Changelog Updater
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  changelog-updater:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
#       - uses: actions/checkout@v3
#         with:
#           # Depending on your needs, you can use a token that will re-trigger workflows
#           # See https://github.com/stefanzweifel/git-auto-commit-action#commits-of-this-action-do-not-trigger-new-workflow-runs
#           token: ${{ secrets.GITHUB_TOKEN }}

      - name: modify changelog
        id: modify-changelog
        uses: dangoslen/dependabot-changelog-helper@v3
        with:
          version: ${{ needs.setup.outputs.version }}
          activationLabel: 'dependabot'
          changelogPath: './CHANGELOG.md'
          
      - name: commit changes
        run: |
          echo ${{ steps.modify-changelog.outputs }}

      # This step is required for committing the changes to your branch. 
      # See https://github.com/stefanzweifel/git-auto-commit-action#commits-of-this-action-do-not-trigger-new-workflow-runs 
#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_message: "Updated Changelog"
